import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {workbench} from './drawing.mjs';
import {marks} from './marks.mjs';
import {createHash} from 'node:crypto';
import MarkdownIt from 'markdown-it';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
export async function buildRooms({repoRoot,outDir,validatedIssues,publicationIssues}) {
const source=pathToFileURL(repoRoot+'/'),out=pathToFileURL(outDir+'/'),assets=new URL('./',import.meta.url);
await mkdir(new URL('rooms/',out),{recursive:true});
for(const name of ['site.css','material.css','living.css','refinements.css','reading.css','coral.css','site.js','living.js','atmosphere.js','print-motion.js','coral-ink.svg','print-stock.svg','text-ink.svg','tv-grain.svg','tv-wear.svg'])await copyFile(new URL(name,assets),new URL('rooms/'+name,out));
const md=new MarkdownIt({html:false,linkify:false});
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const read=p=>readFile(new URL(p,source),'utf8');
const render=s=>md.render(s).replaceAll('<a href="','<a target="_blank" rel="noopener noreferrer" href="');
const editorialIntros=JSON.parse(await readFile(new URL('editorial-intros.json',assets),'utf8'));
const mediaCorrections=JSON.parse(await readFile(new URL('media-corrections.json',assets),'utf8'));
const dates=validatedIssues.filter(i=>i.issueId>='2026-08-25'&&i.manifest.visibility!=='future_draft').map(i=>i.issueId);
if(!dates.length)return []; 
const categories={fashion:'时装',music:'音乐',objects:'物件',city:'城市'};
const issues=[],proof=[];const routes=[];
for(const date of dates){
 const validated=validatedIssues.find(i=>i.issueId===date);
 const raw=validated.content,m=validated.manifest,r=validated.dailyRadar||validated.retrospectiveIndex,a=validated.artDirection;
 if(!r)throw Error('Missing verified reading index '+date);
 const parts=raw.split(/^## /m),intro=parts.shift().trim().split('\n\n'),title=intro.shift().replace(/^# /,''),en=intro.shift();
 const sections=parts.map(s=>({title:s.slice(0,s.indexOf('\n')).trim(),markdown:s.slice(s.indexOf('\n')+1).trim()}));
 const stories=m.stories.map((s,index)=>{const section=sections[index];if(section.title!==s.title)throw Error('Section mismatch '+date+' '+s.id);const radar=r.items.find(x=>x.included_story_id===s.id||x.id===s.id);if(!categories[radar?.category])throw Error('Missing exact category '+s.id);const correction=mediaCorrections[date+'/'+s.id];return {...s,media:correction?{...s.media,external_image_url:correction.external_image_url,alt:correction.alt,origin_url:correction.origin_url}:s.media,date,issueTitle:title,index,category:radar.category,body:render(section.markdown),markdown:section.markdown,url:`/issues/${date}/stories/${s.id}/`};});
 const svg=await read(`src/site/assets/covers/${date}.svg`);
 const cover=svg.replace(/<svg\b[^>]*>/,tag=>tag.replace(/\saria-label="[^"]*"/g,'').replace('<svg ','<svg class="owned-cover" aria-label="'+esc(title)+'原创封面" '));
 const issue={date,title,en,position:m.editorial_position,intro:render(intro.join('\n\n')),closing:render('## '+sections.at(-1).title+'\n\n'+sections.at(-1).markdown),stories,extras:r.items.filter(x=>!m.stories.some(s=>s.id===(x.included_story_id||x.id))),cover,quote:a.closing_quotation?.text||sections.at(-1).markdown.split('\n\n').at(-1).replace(/[“”"]/g,''),hash:m.source_hashes.content_sha256,url:`/issues/${date}/`};
 issues.push(issue);proof.push({date,stories:stories.length,radar:r.items.length,sha256:createHash('sha256').update(raw).digest('hex'),locked:m.content_lock.sha256});
}
const allStories=issues.slice().reverse().flatMap(i=>i.stories),latest=issues.at(-1);
const preserved=publicationIssues.filter(i=>!dates.includes(i.issue_id));
const legacyCategories=JSON.parse(await readFile(new URL('legacy-categories.json',assets),'utf8'));
const legacyStories=preserved.slice().reverse().flatMap(i=>(i.stories||[]).map((s,index)=>({...s,date:i.issue_id,issueTitle:i.title,index,category:legacyCategories[s.id],url:`/issues/${i.issue_id}/stories/${s.id}/`})));
for(const s of legacyStories)if(!s.category)throw Error('Missing reviewed original category '+s.id);
const archiveStories=[...allStories,...legacyStories];
const legacyCards=legacyStories.map(s=>`<article class="story-card legacy-story" data-catalog-item data-kind="articles" data-date="${s.date}" data-category="${s.category}" data-search="${esc(s.title+' '+s.issueTitle+' '+s.date)}"><div class="card-copy"><p class="meta">${s.date} / ${categories[s.category]}</p><h3><a data-internal href="${s.url}">${esc(s.title)} ↗</a></h3><p class="editorial-deck">${esc(s.english?.deck||'保留最初的文章与陈列。')}</p><a data-internal class="entry-label" href="${s.url}">阅读原版文章 ↗</a></div></article>`).join('');
const preservedCards=preserved.slice().reverse().map(i=>`<article class="issue-card" data-catalog-item data-kind="issues" data-date="${i.issue_id}" data-categories="" data-search="${esc(i.title+' '+i.issue_id)}"><a data-internal href="/issues/${i.issue_id}/"><div class="cover-box">${i.coverAsset?`<img src="/assets/${i.coverAsset}" alt="${esc(i.title)} 原版封面" loading="lazy">`:`<strong>${esc(i.title)}</strong>`}</div><div class="issue-card-copy"><time>${i.issue_id}</time><h3>${esc(i.title)}</h3><span>历史原版 · 保留最初陈列 ↗</span></div></a></article>`).join('');
const label=c=>`${c.toUpperCase()} / ${categories[c]}`;
const link=(url,title,cls='',extra='')=>`<a data-internal href="${esc(url)}" class="${cls}" ${extra}>${title}</a>`;
const mark=(n)=>`<span class="index-mark" aria-hidden="true">${String(n).padStart(2,'0')}</span>`;
function figure(s){return `<figure class="photo" data-photo data-media-kind="${s.media.kind}"><div class="photo-window"><span class="photo-fallback"><b data-photo-status role="status" aria-live="polite">图像暂未载入</b><span>来源与正文仍可阅读。</span><button type="button" data-retry-photo hidden>重试加载 ↻</button></span><img data-external-preview="true" src="${esc(s.media.external_image_url)}" alt="${esc(s.id==='adela-prima-release'?'ADÉLA 官方粉色三心图形':s.media.alt)}" loading="lazy" decoding="async" referrerpolicy="no-referrer" width="1200" height="900"><span class="grain" aria-hidden="true"></span></div><figcaption><span>${esc(s.media.credit||s.sources[0].publisher)} <span class="treatment">／原色</span></span><a href="${esc(s.media.origin_url)}" target="_blank" rel="noopener noreferrer">官方图源 ↗</a></figcaption></figure>`;}
function card(s,{archive=false}={}){const intro=editorialIntros[s.date+'/'+s.id];const excerpt=intro?.text||s.markdown.split('\n\n').find(p=>!p.startsWith('来源')&&!p.startsWith('#'))?.replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/[*_]/g,'')||'';return `<article class="story-card" id="card-${s.date}-${s.id}" ${archive?`data-catalog-item data-kind="articles" data-date="${s.date}" data-category="${s.category}" data-search="${esc(s.title+' '+s.english.deck+' '+s.issueTitle+' '+s.date)}"`:''} data-story-category="${s.category}" data-reveal><div class="card-figure">${figure(s)}</div><div class="card-copy"><div class="meta">${mark(s.index+1)}<span class="story-category"><span class="category-en">${s.category.toUpperCase()} / </span>${categories[s.category]}</span><time>${s.date.slice(5).replace('-','.')}</time></div><h3>${link(s.url,esc(s.title)+' <span aria-hidden="true">↗</span>','story-open')}</h3><p class="editorial-kicker">${esc(intro?.kicker||categories[s.category]+'观察')}</p><p class="editorial-deck">${esc(excerpt)}</p><p class="deck">${esc(s.english.deck??'')}</p><div class="card-bottom">${link(`/issues/${s.date}/`,esc(archive?s.issueTitle:'本期 · '+s.date))}${link(s.url,'阅读全文 ↗','entry-label')}</div></div></article>`;}
function issueCard(i,{archive=false}={}){return `<article class="issue-card" id="issue-${i.date}" ${archive?`data-catalog-item data-kind="issues" data-date="${i.date}" data-categories="${[...new Set(i.stories.map(s=>s.category))].join(' ')}" data-search="${esc(i.title+' '+i.date+' '+i.stories.map(s=>s.title+' '+s.english.deck).join(' '))}"`:''} data-reveal>${link(i.url,`<div class="cover-box">${i.cover}<span class="cover-edge" aria-hidden="true"></span></div><div class="issue-card-copy"><div class="meta"><time>${i.date}</time><span>${i.stories.length} 篇</span></div><h3>${esc(i.title)}</h3><ul class="issue-hints">${i.stories.slice(0,3).map(s=>`<li><small>${categories[s.category]}</small>${esc(s.title)}</li>`).join('')}</ul><span class="open-line">进入本期 <span aria-hidden="true">↗</span></span></div>`)}</article>`;}
function controls({home=false}={}){return `<${home?'section':'dialog'} class="room-panel ${home?'room-inline':''}" ${home?'aria-label="选择阅读房间"':'id="room-dialog" aria-labelledby="room-title"'}><div class="room-heading"><h2 id="${home?'home-room-title':'room-title'}">选择你的阅读房间</h2>${home?'<span class="meta">ONE PUBLICATION / THREE ROOMS</span>':'<button class="icon-button" data-close-dialog aria-label="关闭房间选择">×</button>'}</div><div class="room-options" role="group" aria-label="阅读房间">${[['field','Field Notes','场域','纸张、边注与现场'],['coral','Coral Print','印刷','纸与油墨的相遇'],['analog','Analog Signal','信号','旧电视里的文化现场']].map(([k,en,zh,d])=>`<button type="button" data-room="${k}" aria-pressed="${k==='field'}"><span class="swatch swatch-${k}" aria-hidden="true">${marks[k]}</span><span><strong>${en}</strong><em>${zh}</em><small>${d}</small></span><span class="selected-mark" aria-hidden="true">↗</span></button>`).join('')}</div><fieldset class="coral-palette"><legend>纸色与墨色</legend><div class="palette-options" role="group" aria-label="Coral 配色">${[['rose','朱红 · 藕灰','已选方向 · 藕灰与梅墨'],['ash','朱红 · 灰纸','灰纸与青墨'],['mist','朱红 · 雾蓝','雾蓝灰与蓝墨']].map(([k,n,d])=>`<button type="button" data-palette="${k}" aria-pressed="${k==='rose'}"><span class="palette-chip palette-${k}" aria-hidden="true"></span><strong>${n}</strong><small>${d}</small></button>`).join('')}</div></fieldset><div class="room-settings"><label><input data-motion type="checkbox" checked><span class="toggle" aria-hidden="true"></span>动态效果</label><label><input data-filter type="checkbox"><span class="toggle" aria-hidden="true"></span>图片滤镜</label><button data-restore type="button" hidden>恢复原色</button><span data-setting-status role="status" aria-live="polite">图片保持原色</span></div></${home?'section':'dialog'}>`;}
function sources(s){return `<aside class="sources" aria-label="${esc(s.title)} 来源" id="sources-${s.id}" data-reveal><div><span class="eyebrow">Sources &amp; Dates</span><h3>继续核对</h3></div><ol>${s.sources.map((x,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title||x.publisher)} <span aria-hidden="true">↗</span><small>${esc(x.publisher)} · ${esc([x.published_date,x.event_date].filter(Boolean).join(" · "))}</small></a></li>`).join('')}</ol></aside>`;}
function coda(i){return `<footer class="coda" data-reveal>${printMark()}<div class="coda-label"><span>DAILY CODA</span><time>${i.date}</time><span class="room-sign" data-room-sign>FIELD NOTES / 场域</span></div><blockquote>${esc(i.quote)}</blockquote><div class="coda-bottom"><span>Culture & Taste Daily</span>${link('/archive/','继续探索往期 ↗')}<a href="#top">回到顶部 ↑</a></div></footer>`;}
function extras(i){return `<section class="extras section" id="extra-signals" data-reveal><header class="section-heading"><div><p class="eyebrow">02 / FURTHER SIGNALS / ${i.extras.length}</p><h2>本期之外的小线索<span>.</span></h2></div><p>短链接，直达官方现场。与上面的正式文章分开阅读。</p></header><div class="extra-list">${i.extras.map((x,n)=>`<a href="${esc(x.official_url)}" target="_blank" rel="noopener noreferrer"><span class="extra-thumb"><span aria-hidden="true">${String(n+1).padStart(2,'0')}</span>${x.media?.kind==='image'?`<img data-external-preview="true" src="${esc(x.media.url)}" alt="${esc(x.media.alt)}" loading="lazy" decoding="async" referrerpolicy="no-referrer">`:''}</span><span class="extra-copy"><small>${label(x.category)}</small><strong>${esc(x.title)}</strong><span>${esc(x.deck)}</span></span><span class="extra-source">${esc(x.publisher)}<small>补充线索 · 官方来源 ↗</small></span></a>`).join('')}</div></section>`;}
function printMark(){return `<svg class="print-mark" data-print-motion aria-hidden="true" viewBox="0 0 92 18"><path d="M2 10C24 7 47 11 74 7"/><path class="print-register" d="M14 3L14 16M6 9L24 9M60 13L88 11"/></svg>`;}
function printJoin(){return `<div class="print-join" data-print-motion aria-hidden="true"><svg class="print-edge" viewBox="0 0 1440 48" preserveAspectRatio="none"><path d="M0 0H1440V13L1180 15 1065 12 870 17 635 14 412 18 216 13 0 16Z"/><path class="print-register" d="M0 14L216 11 412 16 635 12 870 15 1065 10 1180 13 1440 11V18L1180 20 1065 17 870 22 635 19 412 23 216 18 0 21Z"/></svg>${printMark()}</div>`;}
function hero(i,home=false){return `<section class="hero ${home?'home-hero':'issue-hero'}"><div class="hero-copy"><p class="eyebrow">Culture & Taste Daily <span>${i.date} / ${i.stories.length} 篇</span></p><h1>${i.date==='2026-09-04'?'制作条件<br>被看见':esc(i.title)}</h1><p class="hero-en">${esc(i.en)}</p><p class="hero-position">${esc(i.position)}</p>${link(home?i.url:'#issue-contents',home?'阅读完整本期 ↗':'进入本期目录 ↓','hero-link')}${marks.underline}<div class="hero-foot"><span>FASHION · MUSIC · OBJECTS · CITY</span></div></div><div class="hero-art" data-material data-material-date="${i.date}" data-material-title="${esc(i.title)}">${i.date==='2026-09-04'?workbench():''}<div class="material-back" aria-hidden="true"><span>${esc(i.en)}</span><i>${esc(i.position)}</i></div><div class="material-print"><div class="print-shadow" aria-hidden="true"></div><div class="art-surface">${i.cover}<span class="art-glass" aria-hidden="true"></span><span class="fold" aria-hidden="true"></span><span class="tv-caption" aria-hidden="true">PLAY ▷<small>CULTURE & TASTE</small></span></div></div><div class="material-controls"><button data-material-action aria-pressed="false"><span class="action-field">${i.date==='2026-09-04'?'碰一下工作台':'翻开封面'}</span><span class="action-coral">${i.date==='2026-09-04'?'再画一笔':'翻开封面'}</span><span class="action-analog">调一下频道</span>${marks.arrow}</button><span class="material-caption"><span class="action-field">FIELD NOTES / 现场样张</span><span class="action-coral">CORAL PRINT / 纸与油墨</span><span class="action-analog">CULTURE & TASTE · COLOUR TV</span></span></div><p class="material-note" aria-live="polite"></p><span class="sheet-annotation" aria-hidden="true">${marks.arrow}</span></div></section>${printJoin()}`;}

const bootstrap=`(()=>{let s={theme:'field',motion:true,filter:false,palette:'rose'};try{Object.assign(s,JSON.parse(sessionStorage.getItem('ct-art-direction-settings')||'{}'))}catch{}const q=new URLSearchParams(location.search);if(['field','coral','analog'].includes(q.get('theme')))s.theme=q.get('theme');if(!['field','coral','analog'].includes(s.theme))s.theme='field';for(const k of ['motion','filter'])if(['on','off'].includes(q.get(k)))s[k]=q.get(k)==='on';if(['ash','mist','rose'].includes(q.get('palette')))s.palette=q.get('palette');if(!['ash','mist','rose'].includes(s.palette))s.palette='rose';document.documentElement.dataset.palette=s.palette;document.documentElement.dataset.theme=s.theme;document.documentElement.dataset.filter=s.filter?'on':'off';document.documentElement.dataset.motion=s.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches?'on':'off';window.__CTSettings=s;document.documentElement.classList.add('js')})();`;
function shell(title,body,{type='home',issue=latest}={}){body=body.replace(/(<header class="(?:section-heading|article-header|archive-title section)"[^>]*>)/g,'$1'+printMark());return `<!DOCTYPE html><html lang="zh-CN" data-theme="field" data-motion="off" data-filter="off"><head><style>:focus-visible{outline:2px solid currentColor;outline-offset:4px}</style><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><meta name="color-scheme" content="light dark"><title>${esc(title)} · Culture & Taste</title><script>${bootstrap}</script><link rel="icon" href="/assets/culture-taste-earth.png"><link rel="stylesheet" href="/rooms/site.css"><link rel="stylesheet" href="/rooms/material.css"><link rel="stylesheet" href="/rooms/living.css"><link rel="stylesheet" href="/rooms/refinements.css"><link rel="stylesheet" href="/rooms/reading.css"><link rel="stylesheet" href="/rooms/coral.css"><script src="/rooms/site.js" defer></script><script src="/rooms/living.js" defer></script><script src="/rooms/atmosphere.js" defer></script><script src="/rooms/print-motion.js" defer></script></head><body data-reader="rooms-v2" data-content-sha256="${issue.hash}" class="page-${type}" id="top"><div class="paper-atmosphere" aria-hidden="true"></div><div class="tv-screen-edge" aria-hidden="true"></div><a class="skip skip-link" href="#main">跳到正文</a><header class="masthead">${link('/','Culture <i>&</i> Taste <small>Daily</small>','brand','aria-label="Culture & Taste Daily 首页"')}<nav aria-label="主要导航">${link('/','最新')}${link('/archive/','往期')}${link('/archive/?view=articles','文章')}</nav><button class="room-trigger" data-open-dialog aria-haspopup="dialog"><span class="room-drawing"><i class="action-field">${marks.field}</i><i class="action-coral">${marks.coral}</i><i class="action-analog">${marks.analog}</i></span><span data-current-room>场域</span><span aria-hidden="true">⌄</span></button></header><div class="page-rail" aria-hidden="true"><span data-room-sign>FIELD NOTES</span><i><b data-progress-bar></b></i><span data-progress>00</span></div>${controls()}<main id="main">${body}${coda(issue)}</main><footer class="preview-note">NON-PRODUCTION PREVIEW · 最新 ${latest.date} · <a href="/history/">版本历史 ↗</a></footer><svg class="filter-defs" aria-hidden="true"><filter id="paper-grain"><feTurbulence type="fractalNoise" baseFrequency=".85" numOctaves="3" stitchTiles="stitch"/></filter></svg></body></html>`;}
function television(i){return `<section class="television" aria-label="Culture & Taste 电视首页"><div class="tv-osd"><span>CULTURE & TASTE</span><span data-channel-indicator>CH 00 / 本期</span></div><div class="tv-stage" data-tv-stage><div class="broadcast-cover"><p>${i.date} · ${i.stories.length} 篇</p><h1>${esc(i.title)}</h1><p class="broadcast-en">${esc(i.en)}</p><div class="broadcast-art">${i.cover}</div><p class="broadcast-position">${esc(i.position)}</p>${link(i.url,'阅读本期 ↗','broadcast-read')}</div></div><div class="tv-guide"><span class="tv-guide-label">节目单</span><div class="tv-channel-buttons" role="group" aria-label="切换频道"><button data-channel="0" aria-pressed="true">00 本期</button>${i.stories.map((s,n)=>`<button data-channel="${n+1}" aria-pressed="false">${String(n+1).padStart(2,'0')} ${categories[s.category]}</button>`).join('')}</div><div class="tv-zap"><button data-channel-step="-1" aria-label="上一个频道">CH −</button><button data-channel-step="1" aria-label="下一个频道">CH +</button></div></div><p class="tv-channel-status" aria-live="polite">本期：${esc(i.title)}</p><span class="television-glass" aria-hidden="true"></span></section><template data-channel-template="0"><div class="broadcast-cover"><p>${i.date} · ${i.stories.length} 篇</p><h1>${esc(i.title)}</h1><p class="broadcast-en">${esc(i.en)}</p><div class="broadcast-art">${i.cover}</div><p class="broadcast-position">${esc(i.position)}</p>${link(i.url,'阅读本期 ↗','broadcast-read')}</div></template>${i.stories.map((s,n)=>`<template data-channel-template="${n+1}"><article class="broadcast-story"><div class="broadcast-photo">${figure(s)}</div><div class="broadcast-copy"><p>${s.date} / ${categories[s.category]}</p><h1>${esc(s.title)}</h1><p class="broadcast-en">${esc(s.english.deck??'')}</p>${link(s.url,'进入这篇文章 ↗','broadcast-read')}</div></article></template>`).join('')}`;}
function normalizeHtml(html){
  let svgIndex=0;
  html=html.replace(/<svg\b[\s\S]*?<\/svg>/g,svg=>{
    if(!/^<svg[^>]*\brole=/.test(svg))svg=svg.replace('<svg ','<svg role="img" ');
    if(svg.includes('class="filter-defs"'))return svg;
    const prefix='art-'+(++svgIndex)+'-';
    const ids=[...svg.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
    for(const id of ids){svg=svg.replaceAll(`id="${id}"`,`id="${prefix}${id}"`).replaceAll(`url(#${id})`,`url(#${prefix}${id})`).replaceAll(`href="#${id}"`,`href="#${prefix}${id}"`);}
    svg=svg.replace(/aria-labelledby="([^"]+)"/g,(_,v)=>`aria-labelledby="${v.split(' ').map(id=>ids.includes(id)?prefix+id:id).join(' ')}"`);
    return svg;
  });
  return html.split(/(<script[\s\S]*?<\/script>)/g).map(part=>part.startsWith('<script')?part:part.replace(/&(?!#\d+;|#x[\da-f]+;|[a-z]+;)/gi,'&amp;')).join('');
}
async function page(url,html){const p=url==='/'?'index.html':url.slice(1)+'index.html';await mkdir(new URL(p.substring(0,p.lastIndexOf('/')+1)||'.',out),{recursive:true});html=normalizeHtml(html);const depth=url==='/'?0:url.split('/').filter(Boolean).length;const prefix=depth?'../'.repeat(depth):'./';html=html.replace(/(href|src)="\/(?!\/)([^"]*)"/g,(_,attr,value)=>`${attr}="${prefix}${value}"`).replace(/<button(?![^>]*\btype=)/g,'<button type="button"');await writeFile(new URL(p,out),html);routes.push(url);}
function categorizedStories(i){return `<section class="section daily-stories" id="stories"><header class="section-heading"><div><p class="eyebrow">01 / IN THIS ISSUE</p><h2>本期文章 <span>/ ${i.stories.length}</span></h2></div><p>时装、音乐、物件与城市。<br>从你关心的地方开始读。</p></header><nav class="category-jumps" aria-label="筛选本期分类"><button data-home-category="all" aria-pressed="true">全部 <small>${i.stories.length}</small></button>${Object.entries(categories).map(([k,v])=>`<button data-home-category="${k}" aria-pressed="false">${v} <small>${i.stories.filter(s=>s.category===k).length}</small></button>`).join('')}</nav><p class="home-filter-status" role="status" aria-live="polite">本期正式文章 · ${i.stories.length} 篇</p><div class="category-board uniform-stories">${i.stories.map(s=>card(s)).join('')}</div><p class="home-empty" hidden>本期暂无这一类正式文章，可继续看补充线索。</p></section>`;}
await page('/',shell('最新一期',`<section class="reading-start" aria-label="阅读入口"><div><span class="eyebrow">最新收录一期</span><strong>${latest.date}</strong><span>${latest.stories.length} 篇文章 · ${latest.extras.length} 条补充线索</span></div><nav aria-label="首页内容">${link(latest.url,'读完整本期 ↗')}<a href="#stories">按四类选读 ↓</a><a href="#extra-signals">补充线索 ↓</a>${link('/archive/','找往期 ↗')}</nav></section>${television(latest)}${hero(latest,true)}${categorizedStories(latest)}${extras(latest)}<section class="section week-section"><header class="section-heading"><div><p class="eyebrow">03 / PREVIOUS ISSUES</p><h2>再往前读<span>.</span></h2></div>${link('/archive/','按月份找往期 ↗','text-link')}</header><div class="issue-grid">${issues.slice(0,-1).reverse().slice(0,3).map(i=>issueCard(i)).join('')}</div></section>`));
await page('/archive/',shell('阅读档案',`<header class="archive-title section"><p class="eyebrow">CULTURE & TASTE / ARCHIVE</p><h1>ARCHIVEs</h1><p>${publicationIssues.length} 期刊物 / ${archiveStories.length} 篇正式文章 · 按月份找时间，按标题找内容。</p></header><section class="catalog section" id="catalog"><div class="catalog-tools"><div class="catalog-tabs" role="group" aria-label="档案浏览方式"><button data-view="issues" aria-pressed="true">按期浏览 <small>${publicationIssues.length}</small></button><button data-view="articles" aria-pressed="false">全部文章 <small>${archiveStories.length}</small></button></div><div class="article-tools"><label class="search-label"><span>搜索期刊与文章</span><input type="search" id="catalog-search" placeholder="日期、标题、人物或品牌" autocomplete="off"></label><label class="month-label"><span>收录月份</span><select id="catalog-month"><option value="all">全部月份</option>${[...new Set(issues.map(i=>i.date.slice(0,7)))].reverse().map(m=>`<option value="${m}">${m.replace('-',' 年 ')} 月</option>`).join('')}</select></label><div class="category-tabs" role="group" aria-label="文章分类"><button data-category-filter="all" aria-pressed="true">全部</button>${Object.entries(categories).map(([k,v])=>`<button data-category-filter="${k}" aria-pressed="false">${v}</button>`).join('')}</div></div><div class="catalog-feedback"><p class="catalog-status" role="status" aria-live="polite"></p><button class="catalog-reset" data-clear-search>清除筛选</button></div></div><div class="week-heading"><span>由新到旧</span><span>每页最多 12 期</span></div><div class="catalog-items issue-grid" data-catalog="issues">${issues.slice().reverse().map(i=>issueCard(i,{archive:true})).join('')}${preservedCards}</div><div class="catalog-items article-catalog" data-catalog="articles"><h2 class="nojs-title">全部文章</h2>${allStories.map(s=>card(s,{archive:true})).join('')}${legacyCards}</div><div class="empty-state" hidden><span>∅</span><h2>这里暂时没有匹配的内容。</h2><p>试试其他关键词、月份，或清除筛选。</p></div><nav class="pagination" aria-label="档案分页"></nav><noscript><p>静态阅读模式：所有期刊与文章列于下方，搜索与筛选需启用 JavaScript。</p></noscript></section>`,{type:'archive'}));
for(const i of issues){
 const toc=`<nav class="issue-toc" id="issue-contents" aria-label="本期目录"><p class="eyebrow">CONTENTS / ${i.stories.length}</p>${i.stories.map(s=>`<a href="#story-${s.id}">${mark(s.index+1)}<span>${esc(s.title)}</span><small>${categories[s.category]}</small></a>`).join('')}</nav>`;
 const articles=i.stories.map(s=>`<article class="issue-story" id="story-${s.id}" data-reveal><div class="issue-story-label">${mark(s.index+1)}<span>${label(s.category)}</span></div><div class="issue-story-body"><h2>${link(s.url,esc(s.title)+' ↗')}</h2><p class="article-deck">${esc(s.english.deck??'')}</p>${figure(s)}<div class="prose" data-source-body="${s.id}">${s.body}<div class="english-summary" lang="en"><strong>${esc(s.english.title)}</strong><p>${esc(s.english.abstract)}</p></div></div>${sources(s)}${link(s.url,'单独阅读这篇 ↗','text-link')}</div></article>`).join('');
 await page(i.url,shell(i.title,`${hero(i)}<section class="issue-opening section"><div class="intro-copy prose">${i.intro}</div>${toc}</section><section class="issue-body section">${articles}<div class="issue-exit prose" data-reveal>${i.closing}</div></section>${extras(i)}`,{type:'issue',issue:i}));
 for(const s of i.stories){const position=allStories.findIndex(x=>x.date===s.date&&x.id===s.id),prev=allStories[position-1],next=allStories[position+1];
 const neighbor=(n,d)=>n?link(n.url,`<small>${d}</small><strong>${esc(n.title)}</strong><span>${n.date} / ${categories[n.category]} ↗</span>`):link('/archive/?view=articles',`<small>${d==='上一篇'?'已到最新一篇':'已到本次档案起点'}</small><strong>返回全部文章</strong><span>继续探索 ↗</span>`);
 await page(s.url,shell(s.title,`<div class="breadcrumbs">${link(i.url,'← '+esc(i.title),'back-issue')}<span>${s.date} / ${s.index+1} OF ${i.stories.length}</span></div><article class="article-layout"><aside class="article-aside" aria-label="阅读进度"><div class="sticky-note"><p class="eyebrow">${label(s.category)}</p><span class="article-number">${String(s.index+1).padStart(2,'0')}</span><div class="reading-meter"><i data-progress-bar></i></div><p>阅读位置 <span data-progress>00</span>%</p><a href="#article-sources">来源索引 ↓</a>${link(i.url+'#story-'+s.id,'返回所属期刊 ←')}${link(i.url+'original-edition.html','本期原版陈列 ↗')}</div></aside><div class="article-main"><header class="article-header" data-reveal><p class="eyebrow">${s.date} / ${label(s.category)}</p><h1>${esc(s.title)}</h1><p class="article-deck">${esc(s.english.deck??'')}</p></header>${figure(s)}<div class="prose" id="article-body" data-source-body="${s.id}">${s.body}<div class="english-summary" lang="en"><strong>${esc(s.english.title)}</strong><p>${esc(s.english.abstract)}</p></div></div><div id="article-sources">${sources(s)}</div><div class="article-return">${link(i.url,'← 返回本期目录')}<button data-back-results hidden>返回筛选结果 ↩</button></div></div></article><nav class="neighbor-stories section" aria-label="前后文章">${neighbor(prev,'上一篇')}${neighbor(next,'下一篇')}</nav>`,{type:'article',issue:i}));
 }
}
await writeFile(new URL('content-index.json',out),JSON.stringify({issues:issues.map(i=>({date:i.date,title:i.title,url:i.url,stories:i.stories.length})),articles:archiveStories.map(({id,title,date,category,url,index})=>({id,title,date,category,url,index}))},null,2));
await writeFile(new URL('provenance.json',out),JSON.stringify({pages:routes.length,routes,issues:proof,articles:allStories.length,radar:proof.reduce((n,i)=>n+i.radar,0),extras:issues.reduce((n,i)=>n+i.extras.length,0),source_modified:false,editorial_intros:'Descriptions derived from locked articles; original text unchanged',media_corrections:mediaCorrections,original_photos:'Linked to official sources; no downloads or license changes',theme_coda_override:'Preview presentation only; quotations and source palettes unchanged',renderer_version:'rooms-v2'},null,2));
return dates;
}
